title: Viktor Vereckei | DevOps and Platform Engineer
description: >- 
  I turn ideas into scalable distributed production deployments
  with full ownership and product mindset.

github_username: vverecke
url: "https://vverecke.github.io"

# Build settings
#remote_theme: pages-themes/slate@v0.2.0
theme: jekyll-theme-slate
plugins:
  - jekyll-remote-theme
  - github-pages

show_downloads: false
